# Generated by Django 5.0.7 on 2024-10-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=3)),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
